workflows:
  ios-selfsigned:
    name: iOS SelfSigned Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        CERT_PASSWORD: Encrypted(your_password_here)
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS IPA without signing
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      ios:
        provisioning_profile_path: ios/Runner/MyProfile.mobileprovision
        certificate_path: ios/Runner/MyCert.p12
        certificate_password: $CERT_PASSWORD