workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini
    environment:
      flutter_channel: stable
      flutter_version: 3.41.4
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release