workflows:
  ios-simulator:
    name: iOS Simulator
    instance_type: mac_mini
    environment:
      flutter_channel: stable
      flutter_version: 3.41.4
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build for simulator
        script: |
          flutter build ios --simulator